<a href="https://colab.research.google.com/github/sudheesanamp2003/dev-assignment-1/blob/main/Untitled51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from statsmodels.stats import weightstats as stests
     

df = pd.read_csv('/content/breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:

df[['texture_mean','perimeter_mean']].describe()

       texture_mean  perimeter_mean
count    569.000000      569.000000
mean      19.289649       91.969033
std        4.301036       24.298981
min        9.710000       43.790000
25%       16.170000       75.170000
50%       18.840000       86.240000
75%       21.800000      104.100000
max       39.280000      188.500000

In [9]:
ztest ,pvalue = stests.ztest(df['texture_mean'], x2=None, value=146)
print(float(pvalue))
print(ztest)

0.0
-702.7408095479943

In [10]:
if pvalue<0.05:
    print("Null hyphothesis rejected , Alternative hyphothesis accepted")
else:
    print("Null hyphothesis accepted , Alternative hyphothesis rejected")

Null hyphothesis rejected , Alternative hyphothesis accepted

In [11]:
ztest,pval1=stests.ztest(df['texture_mean'],df['perimeter_mean'],value=100)
print(float(pval1))
print(ztest)

0.0
-166.92046768740826

In [12]:
if pval1<0.05:
    print("Null hyphothesis rejected , Alternative hyphothesis accepted")
else:
    print("Null hyphothesis accepted , Alternative hyphothesis rejected")

Null hyphothesis rejected , Alternative hyphothesis accepted